### ISSUE TITLE
Something is not going right

### ISSUE THREAD

**Issue by up2smoke** [Palatis/XAppDebug#13]
Modullog:
`[ 2024-09-26T08:28:13.500     1000:  1604:  1736 I/LSPosed-Bridge  ] XAppDebug: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference in method 'void tw.idv.palatis.xappdebug.xposed.HookMain$a.afterHookedMethod(NaodocNEP.ZChvrO.zPPaC.XC_MethodHook$MethodHookParam)'
	at tw.idv.palatis.xappdebug.xposed.HookMain$a.afterHookedMethod(Unknown Source:6)
	at NaodocNEP.ZChvrO.zPPaC.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.getPackageInfo(Unknown Source:25)
	at com.android.server.pm.InstallPackageHelper.handlePackagePostInstall(InstallPackageHelper.java:2971)
	at com.android.server.pm.PackageHandler.doHandleMessage(PackageHandler.java:120)
	at com.android.server.pm.PackageHandler.handleMessage(PackageHandler.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)`

Advancelog:
`[ 2024-09-26T08:28:13.500     1000:  1604:  1736 I/LSPosed-Bridge  ] XAppDebug: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference in method 'void tw.idv.palatis.xappdebug.xposed.HookMain$a.afterHookedMethod(NaodocNEP.ZChvrO.zPPaC.XC_MethodHook$MethodHookParam)'
	at tw.idv.palatis.xappdebug.xposed.HookMain$a.afterHookedMethod(Unknown Source:6)
	at NaodocNEP.ZChvrO.zPPaC.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.getPackageInfo(Unknown Source:25)
	at com.android.server.pm.InstallPackageHelper.handlePackagePostInstall(InstallPackageHelper.java:2971)
	at com.android.server.pm.PackageHandler.doHandleMessage(PackageHandler.java:120)
	at com.android.server.pm.PackageHandler.handleMessage(PackageHandler.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)`

I'm using:
Magisk 26.4
Lsposed 1.9.4 (API 100)
Android 13
MIUI 14
Xiaomi 11T Phone

**Comment by peterysch** [comment]
Fixed in 895dc2658b80ec0264454b328696b79c62e8dc27.

You need to compile the APK yourself.

**Comment by wsyhj1** [comment]
Hello bloggers:
I seem to have hooked to WeChat, but I didn't get the recording file.
After this module hooks to WeChat, how to get WeChat call recordings, do I need a recording app to record?
I am a novice, please let me know how to use it carefully. Thank you so much!

----part 2 start----
[ 2025-08-14T16:43:31.492    10210: 26898: 26898 I/LSPosed-Bridge  ] Loading legacy module com.tsng.hidemyapplist from /data/app/com.tsng.hidemyapplist-AH-F2sF9Ry95RriKldE6ZQ==/base.apk
[ 2025-08-14T16:43:31.642    10210: 26898: 26898 I/LSPosed-Bridge  ]   Loading class icu.nullptr.hidemyapplist.xposed.XposedEntry
[ 2025-08-14T16:43:31.708    10210: 26898: 26898 I/LSPosed-Bridge  ] Loading legacy module com.virb3.trustmealready from /data/app/com.virb3.trustmealready-sqaxvABzk_cDBzf54KStLw==/base.apk
[ 2025-08-14T16:43:31.709    10210: 26898: 26898 I/LSPosed-Bridge  ]   Loading class com.virb3.trustmealready.Main
[ 2025-08-14T16:43:31.710    10210: 26898: 26898 I/LSPosed-Bridge  ] TrustMeAlready loading...
[ 2025-08-14T16:43:31.711    10210: 26898: 26898 I/LSPosed-Bridge  ] Hooking method:
[ 2025-08-14T16:43:31.711    10210: 26898: 26898 I/LSPosed-Bridge  ] private java.util.List com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(java.security.cert.X509Certificate[],byte[],byte[],java.lang.String,boolean,java.util.ArrayList,java.util.ArrayList,java.util.Set) throws java.security.cert.CertificateException
[ 2025-08-14T16:43:31.716    10210: 26898: 26898 I/LSPosed-Bridge  ] TrustMeAlready loaded! Hooked 1 methods
[ 2025-08-14T16:43:31.716    10210: 26898: 26898 I/LSPosed-Bridge  ] Loading legacy module io.github.wzhy.xaudiocapture.debug from /data/app/io.github.wzhy.xaudiocapture.debug-0W1Vu6X5oEfRbMnCEaxJzA==/base.apk
[ 2025-08-14T16:43:31.952    10210: 26898: 26898 I/LSPosed-Bridge  ]   Loading class io.github.wzhy.xaudiocapture.xposed.HookMain
[ 2025-08-14T16:43:31.954    10210: 26898: 26898 I/LSPosed-Bridge  ]   Loading class io.github.wzhy.xaudiocapture.xposed.HookSelf
[ 2025-08-14T16:43:32.265    10210: 26898: 26898 I/LSPosed-Bridge  ] [XAudioCapture]: com.tencent.mm Hooked!
[ 2025-08-14T16:43:35.196    10210: 27083: 27083 I/LSPosed-Bridge  ] Loading legacy module com.tsng.hidemyapplist from /data/app/com.tsng.hidemyapplist-AH-F2sF9Ry95RriKldE6ZQ==/base.apk
[ 2025-08-14T16:43:35.360    10210: 27083: 27083 I/LSPosed-Bridge  ]   Loading class icu.nullptr.hidemyapplist.xposed.XposedEntry
[ 2025-08-14T16:43:35.423    10210: 27083: 27083 I/LSPosed-Bridge  ] Loading legacy module com.virb3.trustmealready from /data/app/com.virb3.trustmealready-sqaxvABzk_cDBzf54KStLw==/base.apk
[ 2025-08-14T16:43:35.424    10210: 27083: 27083 I/LSPosed-Bridge  ]   Loading class com.virb3.trustmealready.Main
[ 2025-08-14T16:43:35.425    10210: 27083: 27083 I/LSPosed-Bridge  ] TrustMeAlready loading...
[ 2025-08-14T16:43:35.426    10210: 27083: 27083 I/LSPosed-Bridge  ] Hooking method:
[ 2025-08-14T16:43:35.426    10210: 27083: 27083 I/LSPosed-Bridge  ] private java.util.List com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(java.security.cert.X509Certificate[],byte[],byte[],java.lang.String,boolean,java.util.ArrayList,java.util.ArrayList,java.util.Set) throws java.security.cert.CertificateException
[ 2025-08-14T16:43:35.432    10210: 27083: 27083 I/LSPosed-Bridge  ] TrustMeAlready loaded! Hooked 1 methods
[ 2025-08-14T16:43:35.432    10210: 27083: 27083 I/LSPosed-Bridge  ] Loading legacy module io.github.wzhy.xaudiocapture.debug from /data/app/io.github.wzhy.xaudiocapture.debug-0W1Vu6X5oEfRbMnCEaxJzA==/base.apk
[ 2025-08-14T16:43:35.728    10210: 27083: 27083 I/LSPosed-Bridge  ]   Loading class io.github.wzhy.xaudiocapture.xposed.HookMain
[ 2025-08-14T16:43:35.730    10210: 27083: 27083 I/LSPosed-Bridge  ]   Loading class io.github.wzhy.xaudiocapture.xposed.HookSelf
[ 2025-08-14T16:43:36.021    10210: 27083: 27083 I/LSPosed-Bridge  ] [XAudioCapture]: com.tencent.mm Hooked!

**Comment by Palatis** [comment]
this module alone doesn't do recording, it enables the ability for you to attach a debugger onto it (in android studio).
