### ISSUE TITLE
spam log

### ISSUE THREAD

**Issue by voila1106** [Palatis/XAppDebug#9]
```
XAppDebug: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference
    at tw.idv.palatis.xappdebug.xposed.HookMain$e.afterHookedMethod(Unknown Source:6)
    at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
    at LSPHooker_.getPackageInfo(Unknown Source:25)
    at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1956)
    at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8598)
    at android.os.Binder.execTransactInternal(Binder.java:1182)
    at android.os.Binder.execTransact(Binder.java:1146)
```
It works fine, but these logs print frequently.
Android 12, MIUI 14

**Comment by Palatis** [comment]
i dunno, some vendor just modify Android framework heavily, which might not always comply to the AOSP code base.

might have to hook a debugger to see why it's returning `null`.

**Comment by auag0** [comment]
fixed apk
https://github.com/auag0/XAppDebug/releases/tag/1.0.6
